#!/bin/sh
if [ -z $3 ]; then
    echo "USAGE: bajarserie <nombre> <num_max> <extension>"
    echo "USAGE: bajarserie http://www.noticianumeradas.com/diciembre/ 15 .html"
    exit 0;
else
    aa=$2; 
    while ((aa>0)); do 
	echo ; echo " *** ${aa} ** "; echo
        wget $1${aa}${3}; 
        if ((aa<10)); then wget ${1}0${aa}${3}; fi   # Bajar 1.jpg y 01.jpg
        aa=$((aa-1)); 
    done; 
    wget ${1}${3}  # A veces hay un ejemplar sin numerar
fi
