#!/bin/sh
LIMIT=30 # TODO: make this a parameter

INITIAL=`vnstat |grep today |awk '{print($8)}'|awk 'BEGIN{FS="."}{print($1)}'`
FINISHED=false
while [ $FINISHED != "true" ]; do
  NEW=`vnstat |grep today |awk '{print($8)}'|awk 'BEGIN{FS="."}{print($1)}'`
  set_term_title "Network use today: $NEW MB (remaining: $((LIMIT-(NEW-INITIAL))) Mb)"
  if [ $((NEW)) -gt $((INITIAL + LIMIT)) ]; then
    FINISHED="true"
    MSG="Te pasaste (total net use: $NEW MB)!"
    gnome-terminal -e "say_THE_END $MSG" --geometry 120x30+50+50
  fi
  sleep 30
done
set_term_title "Terminal"
    
